config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  root 'site/home#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
    #@admins = Admin.with_restricted_access
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to backoffice_admins_path, notice: I18n.t('messages.created_with', item: @admin.name)
    else
      render :new
    end
  end

  def edit
    # Uses the before_action to set the admin.
  end

  def update
    if @admin.update(admin_params)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: I18n.t('messages.updated_with', item: @admin.name)
    else
      render :edit
    end
  end

  def destroy
    authorize @admin
    admin_name = @admin.name

    if @admin.destroy
      redirect_to backoffice_admins_path, notice: I18n.t('messages.destroyed_with', item: admin_name)
    else
      render :index
    end
  end

  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def admin_params
      if password_blank?
        params[:admin].except!(:password, :password_confirmation)
      end

      if @admin.blank?
        params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
      else
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

    def password_blank?
      params[:admin][:password].blank? &&
      params[:admin][:password_confirmation].blank?
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(category_params)

    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "Category (#{@category.description}) created success"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to backoffice_categories_path, notice: "Category (#{@category.description}) updated success"
    else
      render :edit
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:description)
    end
end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
  def index
    %x(bundle exec erd --filename='public/diagram')
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin,
                               params[:'recipient-text'],
                               params[:'subject-text'],
                               params['message-text']).deliver_now

      @notify_message = I18n.t('messages.email_delivered')
      @notify_flag = "success"
    rescue
      @notify_message = I18n.t('messages.email_not_delivered')
      @notify_flag = "error"
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin #current user to pundit
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/_form.html.erb
<h1 class="page-header">Admins</h1>
<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        <ul>
            <%= @admin.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "form-control", placeholder: "Admin name"  %>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, type: "email", class: "form-control", placeholder: "Ex: admin@admin.com"  %>
                </div>
                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role %>
                        <%= f.collection_radio_buttons :role, options_for_roles, :id, :description do |b| %>
                            <div class="radio">
                                <label>
                                    <%= b.label { b.radio_button + b.text } %>
                                </label>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.password_field :password, type: "password", class: "form-control", placeholder: "Password" %>
                </div>
                <div class="form-group">
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, type: "password", class: "form-control", placeholder: "Password Confirmation" %>
                </div>
                <%= f.submit "Submit", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/backoffice/admins/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-text" class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
          </div>
          <div class="form-group">
            <label for="subject-text" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, class: "form-control", required: "required") %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag t('buttons.send_message'), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/form", locals: {action: "Edit Admin"} %>

app/views/backoffice/admins/index.html.erb
<!-- Page Content -->

<h1 class="page-header"><%= @admins.model_name.human(count: @admins) %></h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= t('messages.listing', model: @admins.model_name.human(count: @admins)) %>
        <% if policy(@admins).new?  %>
            <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle pull-right", style: "margin-top:-5px" do %>
                <i class="fa fa-plus"></i>
            <% end %>
        <% end %>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><%= @admins.model.human_attribute_name('name') %></th>
                        <th><%= @admins.model.human_attribute_name('email') %></th>
                        <th><%= @admins.model.human_attribute_name('role') %></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.email %></td>
                            <td><%= admin.role_i18n %></td>
                            <td>
                                <%= link_to edit_backoffice_send_mail_path(admin), class: "btn btn-info btn-circle", remote: true do %>
                                    <i class="fa fa-envelope"></i>
                                <% end %>
                                <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>
                                <% if current_admin.id != admin.id && policy(@admins).destroy? %>
                                    <%= link_to backoffice_admin_path(admin),
                                        method: :delete,
                                        class: "btn btn-danger btn-circle",
                                        data: {confirm: t('messages.confirm_with', item: admin.name )} do %>
                                        <i class="fa fa-times"></i>
                                    <% end %>
                                <% else %>
                                    <%= link_to '#', disabled: 'disabled', class: 'btn btn-danger btn-circle' do  %>
                                        <i class="fa fa-times"></i>
                                    <% end %>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<%= render partial: 'backoffice/admins/send_mail_modal' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/form", locals: {action: "New Admin"} %>