config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  root 'site/home#index'

end

app/controllers/site/ad_detail_controller.rb
class Site::AdDetailController < SiteController

  def show
    @categories = Category.order_by_description
    @ad = Ad.find(params[:id])
  end
end

app/controllers/site/categories_controller.rb
class Site::CategoriesController < SiteController

  def show
    @categories = Category.order_by_description
    @category = Category.friendly.find(params[:id])
    @ads = Ad.by_category(@category, params[:page])
  end
end

app/controllers/site/comments_controller.rb
class Site::CommentsController < SiteController

  before_action :authenticate_member!

  def create
    @comment = Comment.new(comment_params)
    @comment.member = current_member

    if @comment.save
      redirect_to site_ad_detail_path(@comment.ad_id), notice: "Comentário adicionado!"
    else
      redirect_to site_ad_detail_path(@comment.ad_id), notice: "Erro ao adicionar comentário!"
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :ad_id)
    end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(params[:page])
    @carousel = Ad.random(4)
  end
end

app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController
  before_action :set_ad, only: [:edit, :update]

  def index
    @ads = Ad.to_the(current_member)
  end

  def edit
    # Se Ad via before_action
  end

  def update
    if @ad.update(params_ad)
      redirect_to site_profile_ads_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member

    if @ad.save
      redirect_to site_profile_ads_path, notice: "Anúncio cadastrado com sucesso!"
    else
      render :new
    end
  end

  private

    def set_ad
      @ad = Ad.find(params[:id])
    end

    def params_ad
      params.require(:ad).permit(:id, :title, :category_id, :price, :description, :description_md, :description_short, :picture, :finish_date)
    end

end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController
  def index
    #
  end
end

app/controllers/site/profile/my_data_controller.rb
class Site::Profile::MyDataController < Site::ProfileController
  before_action :set_profile_member, only: [:edit, :update]

  def edit
  end

  def update
    if @profile_member.update(params_profile_member)
      redirect_to edit_site_profile_my_datum_path(current_member.id), notice: "Perfil atualizado com sucesso!"
    else
      render :edit
    end
  end

  private

    def set_profile_member
      @profile_member = ProfileMember.find_or_create_by(member_id: current_member.id)
    end

    def params_profile_member
      params.require(:profile_member).permit(:id, :first_name, :second_name, :birthdate)
    end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout "profile"
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController

  def ads
    @ads = Ad.search(params[:q], params[:page])
    @categories = Category.all
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/helpers/site/profile/my_data_helper.rb
module Site::Profile::MyDataHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/layouts/elements/site/_carousel.html.erb
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <%= link_to (image_tag @carousel.first.picture.url(:large)), site_ad_detail_path(@carousel.first), remote: true, data: { push: :partial}, class: "slide-image" %>
                </div>
                <div class="item">
                    <%= link_to (image_tag @carousel.second.picture.url(:large)), site_ad_detail_path(@carousel.second), remote: true, data: { push: :partial}, class: "slide-image" %>
                </div>
                <div class="item">
                    <%= link_to (image_tag @carousel.third.picture.url(:large)), site_ad_detail_path(@carousel.third), remote: true, data: { push: :partial}, class: "slide-image" %>
                </div>
                <div class="item">
                    <%= link_to (image_tag @carousel.fourth.picture.url(:large)), site_ad_detail_path(@carousel.fourth), remote: true, data: { push: :partial}, class: "slide-image" %>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

app/views/layouts/elements/site/_footer.html.erb
<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; <%= t('app.name') %> <%= Date.today.year %></p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

app/views/layouts/elements/site/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to t('app.name'), root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
                <% unless member_signed_in? %>
                    <li>
                        <%= link_to "#{t('top_menu.sign_in')}", new_member_session_path %>
                    </li>
                    <li>
                        <%= link_to "#{t('top_menu.sign_up')}", new_member_registration_path %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to current_member.email, "#" %>
                    </li>
                    <li>
                        <%= link_to "#{t('top_menu.profile')}", site_profile_dashboard_index_path %>
                    </li>
                    <li>
                        <%= link_to "#{t('top_menu.logout')}", destroy_member_session_path, method: :delete %>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/elements/site/_sidebar.html.erb
<div id="home-sidebar" class="col-md-3">
    <p class="lead"><%= @categories.first.model_name.human(count: 2) %></p>
    <div class="list-group">
        <% @categories.each do |category| %>
            <%= link_to "#{category.description} (#{category.ads_count})", site_category_path(category), class: "list-group-item" %>
        <% end %>
    </div>
</div>