config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base

  # Constants
  QTT_PER_PAGE = 6

  # RatyRate gem
  ratyrate_rateable 'quality'

  # Callbacks
  before_save :md_to_html

  # Associations
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  # Validates
  validates :title, :description_md, :description_short, :category, presence: true
  validates :picture, :finish_date, presence: true
  validates :price, numericality: { greater_than: 0 }

  # Scopes
  scope :descending_order, ->(page) {
    order(created_at: :desc).page(page).per(QTT_PER_PAGE)
  }

  scope :search, ->(term, page) {
    where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(QTT_PER_PAGE)
  }

  scope :to_the, ->(member) { where(member: member) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(QTT_PER_PAGE) }

  scope :random, ->(quantity) {
    if Rails.env.production?
      limit(quantity).order("RAND()") # MySQL
    else
      limit(quantity).order("RANDOM()") # SQLite
    end
  }

  # Paperclip
  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # gem money-rails
  monetize :price_cents

  private
    def md_to_html
      options = {
        filter_html: true,
        link_attributes: {
          rel: "nofollow",
          target: "_blank"
        }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)
    end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # def self.with_full_access
  #   where(role: 'full_access')
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base

  # Gem Friendly Id
  include FriendlyId
  friendly_id :description, use: :slugged

  # Associations
  has_many :ads

  # Validations
  validates_presence_of :description

  # Scopes
  scope :order_by_description, -> { order(:description) }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ActiveRecord::Base

  # RatyRate gem
  ratyrate_rater

  # Associations
  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  # Validations
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nested_attributes
    if profile_member.first_name.blank?
      errors.add(:base, "É necessário preencher o campo Primeiro nome.")
    end
    if profile_member.second_name.blank?
      errors.add(:base, "É necessário preencher o campo Segundo nome.")
    end
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_member.rb
class ProfileMember < ActiveRecord::Base
  belongs_to :member

  def full_name
    "#{self.first_name} #{self.second_name}"
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :store_current_location, :unless => :devise_controller?

  # Pundit
  include Pundit

  # Manage Punit Errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = I18n.t('messages.not_authorized')
    redirect_to(request.referrer || root_path)
  end

  private

    def store_current_location
      store_location_for(:member, request.url)
    end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin #current user to pundit
  end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  def new
    build_resource({})
    resource.build_profile_member
    respond_with self.resource
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
        :sign_up,
        keys:[
          :email, :password, :password_confirmation,
          :profile_member_attributes => [:first_name, :second_name]
        ]
    )
  end

end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController

  def new
    super do |resource|
      resource.build_profile_member
    end
  end

  protected
    def after_sign_in_path_for(resource)
      stored_location = stored_location_for(resource)

      if stored_location.match(site_ad_detail_index_path)
        stored_location
      else
        site_profile_dashboard_index_path
      end
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_member
  end

  def devise_sign_in?
    params[:controller] == 'members/sessions' ? '' : 'display:none;'
  end

  def devise_sign_up?
    params[:controller] == 'members/registrations' ? '' : 'display:none;'
  end
end

app/helpers/members/registrations_helper.rb
module Members::RegistrationsHelper
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/members/shared/_form.html.erb
<div class="container">
    <div id="loginbox" style="<%= devise_sign_in? %> margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title"><%= t('labels.login') %></div>
                <div style="float:right; font-size: 80%; position: relative; top:-18px">
                    <%= link_to t('labels.forgot_passoword'), new_member_password_path %>
                </div>
            </div>

            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "form-horizontal", role:"form" }) do |f| %>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <%= f.email_field :email, autofocus: true, class:"form-control", placeholder:"Email" %>
                    </div>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"Senha" %>
                    </div>

                    <div class="input-group">
                      <div class="checkbox">
                        <label>
                          <% if devise_mapping.rememberable? -%>
                              <%= f.check_box :remember_me %>
                              Lembrar-me
                          <% end -%>
                        </label>
                      </div>
                    </div>

                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                          <%= f.submit (t('labels.enter')), class: "btn btn-success" %>
                          <a id="btn-fblogin" href="#" class="btn btn-primary" disabled="disabled"><%= t('labels.sign_in_with_facebook') %></a>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 control">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                <%= t('labels.dont_have_an_account') %>
                            <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                <%= t('labels.sign_up_here') %>
                            </a>
                            </div>
                        </div>
                    </div>
                    <% end %>
            </div>
        </div>
    </div>

    <div id="signupbox" style="<%= devise_sign_up? %> margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title"><%= t('labels.sign_up') %></div>
                <div style="float:right; font-size: 85%; position: relative; top:-18px">
                    <a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()"><%= t('labels.login') %></a>
                </div>
            </div>
            <div class="panel-body" >
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: "form-horizontal", role:"form" }) do |f| %>

                <div class="form-group">
                    <%= f.label :email, class:"col-md-3 control-label" %>
                    <div class="col-md-9">
                        <%= f.email_field :email, autofocus: true, class:"form-control", placeholder:"Email" %>
                    </div>
                </div>

                <%= f.fields_for :profile_member do |profile_fields| %>
                    <div class="form-group">
                        <%= profile_fields.label :first_name, class:"col-md-3 control-label"  %>
                        <div class="col-md-9">
                            <%= profile_fields.text_field :first_name, class:"form-control", placeholder:"Primeiro nome" %>
                        </div>
                    </div>

                    <div class="form-group">
                        <%= profile_fields.label :second_name, class:"col-md-3 control-label" %>
                        <div class="col-md-9">
                            <%= profile_fields.text_field :second_name, class:"form-control", placeholder:"Segundo nome" %>
                        </div>
                    </div>
                <% end %>

                <div class="form-group">
                    <%= f.label :password, class:"col-md-3 control-label" %>
                    <div class="col-md-9">
                        <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"Senha" %>
                    </div>
                </div>

                <div class="form-group">
                    <%= f.label :password_confirmation, class:"col-md-3 control-label" %>
                    <div class="col-md-9">
                        <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder:"Confirmação da senha" %>
                    </div>
                </div>

                <div class="form-group">
                    <!-- Button -->
                    <div class="col-md-offset-3 col-md-9">
                        <%= f.submit (t('labels.sign_up')), class: "btn btn-info" do %>
                          <i class="icon-hand-right"></i> &nbsp Sign Up
                        <% end %>
                    </div>
                </div>

                <% end %>
             </div>
        </div>
    </div>
</div>

<% flash.each do |key, value| %>
  <%= javascript_tag "$.notify( { message: '#{value}'}, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
<% end %>

<% unless devise_error_messages!.blank? %>
  <% resource.errors.full_messages.each do |message| %>
      <%= javascript_tag "$.notify( { message: '#{message}'}, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
  <% end %>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>